# Generated by Django 6.0.6 on 2026-06-05 15:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_start', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата начала публикации')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания публикации')),
                ('main_photo', models.ImageField(blank=True, max_length=255, null=True, upload_to='news/main/%Y/%m/', verbose_name='Главное фото')),
            ],
        ),
    ]
