# Generated by Django 6.0.6 on 2026-07-22 18:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('excerpt', models.TextField(blank=True, max_length=500, verbose_name='Краткое описание')),
                ('main_photo', models.ImageField(blank=True, null=True, upload_to='news/main/%Y/%m/', verbose_name='Главное фото')),
                ('is_published', models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано')),
                ('date_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата начала публикации')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания публикации')),
                ('meta_title', models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
                ('meta_description', models.TextField(blank=True, max_length=255, verbose_name='SEO описание')),
                ('meta_keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова')),
                ('views', models.IntegerField(default=0, editable=False, verbose_name='Просмотры')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/%Y/%m/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='news.news', verbose_name='Новость')),
            ],
            options={
                'verbose_name': 'Фото галереи',
                'verbose_name_plural': 'Фото галереи',
                'ordering': ['order'],
            },
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-date_start', 'is_published'], name='news_news_date_st_e7bce6_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['slug'], name='news_news_slug_915ecd_idx'),
        ),
    ]
