# Generated by Django 4.2.30 on 2026-08-02

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [('news', '0001_initial')]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Иконка')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории', 'ordering': ['order', 'name']},
        ),
        migrations.CreateModel(
            name='NewsGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news/gallery/%Y/%m/', verbose_name='Изображение')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={'verbose_name': 'Фото галереи', 'verbose_name_plural': 'Фото галереи', 'ordering': ['order']},
        ),
        migrations.AlterModelOptions(name='news', options={'ordering': ['-date_start'], 'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'}),
        migrations.AddField(model_name='news', name='excerpt', field=models.TextField(blank=True, max_length=500, verbose_name='Краткое описание')),
        migrations.AddField(model_name='news', name='is_published', field=models.BooleanField(db_index=True, default=True, verbose_name='Опубликовано')),
        migrations.AddField(model_name='news', name='meta_description', field=models.TextField(blank=True, max_length=255, verbose_name='SEO описание')),
        migrations.AddField(model_name='news', name='meta_keywords', field=models.CharField(blank=True, max_length=255, verbose_name='Ключевые слова')),
        migrations.AddField(model_name='news', name='meta_title', field=models.CharField(blank=True, max_length=255, verbose_name='SEO заголовок')),
        migrations.AddField(model_name='news', name='slug', field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL')),
        migrations.AddField(model_name='news', name='views', field=models.IntegerField(default=0, editable=False, verbose_name='Просмотры')),
        migrations.AlterField(model_name='news', name='content', field=ckeditor.fields.RichTextField(verbose_name='Содержание')),
        migrations.AlterField(model_name='news', name='created_at', field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создано')),
        migrations.AlterField(model_name='news', name='date_start', field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата начала публикации')),
        migrations.AlterField(model_name='news', name='main_photo', field=models.ImageField(blank=True, null=True, upload_to='news/main/%Y/%m/', verbose_name='Главное фото')),
        migrations.AlterField(model_name='news', name='title', field=models.CharField(max_length=255, verbose_name='Заголовок')),
        migrations.AlterField(model_name='news', name='updated_at', field=models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
        migrations.AddIndex(model_name='news', index=models.Index(fields=['-date_start', 'is_published'], name='news_news_date_st_e7bce6_idx')),
        migrations.AddIndex(model_name='news', index=models.Index(fields=['slug'], name='news_news_slug_915ecd_idx')),
        migrations.AddField(
            model_name='newsgallery',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='news.news', verbose_name='Новость'),
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='news.category', verbose_name='Категория'),
        ),
    ]
