# Generated by Django 4.2.30 on 2026-08-02

from django.db import migrations


class Migration(migrations.Migration):
    """Preserve the historical branch without repeating ``0001``.

    This migration was generated from an older project state after the same
    models and fields had already been consolidated into ``0001_initial``.
    Applying its original operations to a fresh database therefore attempted
    to create existing tables and columns. Keeping the node as a no-op retains
    compatibility with databases where it was previously faked as applied.
    """

    dependencies = [('news', '0001_initial')]

    operations = []
