# Generated by Django 6.0.6 on 2026-08-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text='Показывать этот материал в большом блоке на главной странице.',
                verbose_name='Главная новость',
            ),
        ),
    ]
