# Generated by Django 4.2.30 on 2026-08-09 13:13

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Название баннера')),
                ('placement', models.CharField(choices=[('top', 'Верх сайта · 970 × 90'), ('home_sidebar', 'Главная · справа · 300 × 250'), ('home_bottom', 'Главная · нижний баннер · 970 × 90'), ('home_popular', 'Главная · «Читают сейчас» · 300 × 600'), ('section_sidebar', 'Разделы · справа · 300 × 250'), ('section_rail', 'Разделы · нижний правый · 300 × 300'), ('section_bottom', 'Разделы · нижний баннер · 970 × 90'), ('article_sidebar', 'Статья · слева · 240 × 400'), ('article_inline', 'Статья · внутри текста · 680 × 120')], max_length=32, unique=True, verbose_name='Место на сайте')),
                ('image', models.ImageField(upload_to='advertising/%Y/%m/', verbose_name='Изображение баннера')),
                ('link', models.URLField(blank=True, verbose_name='Ссылка при клике')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Описание баннера')),
                ('open_in_new_tab', models.BooleanField(default=True, verbose_name='Открывать ссылку в новой вкладке')),
                ('is_enabled', models.BooleanField(db_index=True, default=True, verbose_name='Показывать баннер')),
                ('date_start', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Показывать с')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Снять с показа')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Рекламный баннер',
                'verbose_name_plural': 'Рекламные баннеры',
                'ordering': ['placement', 'name'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='editorial_status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('scheduled', 'Запланирована'), ('published', 'На сайте')], db_index=True, default='draft', help_text='Черновик не виден читателям. Запланированная новость выйдет в указанное время.', max_length=12, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание'),
        ),
    ]
