# Generated by Django 4.2.30 on 2026-08-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_set_editorial_status_from_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Название тега')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, help_text='Выключи, чтобы временно скрыть тег и его страницу от читателей.', verbose_name='Показывать на сайте')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='Добавь от 1 до 5 меток, по которым читатель сможет найти похожие материалы.', related_name='news_items', to='news.tag', verbose_name='Теги'),
        ),
    ]
