# Generated by Django 6.0.6 on 2026-09-22 07:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_category_legacy_k2_id_news_legacy_k2_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, unique=True, verbose_name='Название источника')),
                ('website_url', models.URLField(verbose_name='Сайт источника')),
                ('feed_url', models.URLField(unique=True, verbose_name='URL ленты или API')),
                ('source_type', models.CharField(choices=[('rss', 'RSS'), ('atom', 'Atom'), ('api', 'API')], default='rss', max_length=8, verbose_name='Тип источника')),
                ('allowed_domains', models.TextField(help_text='Домены через запятую. Ссылки вне списка не загружаются.', verbose_name='Разрешённые домены')),
                ('is_active', models.BooleanField(db_index=True, default=False, verbose_name='Источник включён')),
                ('editorial_approved', models.BooleanField(default=False, verbose_name='Одобрен редакцией')),
                ('legal_approved', models.BooleanField(default=False, verbose_name='Одобрен юридически')),
                ('terms_url', models.URLField(blank=True, verbose_name='Условия использования')),
                ('terms_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Условия проверены')),
                ('robots_reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='robots.txt проверен')),
                ('min_request_interval_minutes', models.PositiveIntegerField(default=60, verbose_name='Минимальный интервал запросов, минут')),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя загрузка')),
                ('notes', models.TextField(blank=True, verbose_name='Редакционные примечания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Разрешённый источник новостей',
                'verbose_name_plural': 'Разрешённые источники новостей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ImportedNewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000, unique=True, verbose_name='Оригинальный URL')),
                ('source_name', models.CharField(max_length=160, verbose_name='Название источника')),
                ('source_title', models.CharField(max_length=500, verbose_name='Оригинальный заголовок')),
                ('source_published_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата оригинала')),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Загружено')),
                ('normalized_text', models.TextField(verbose_name='Нормализованный исходный текст')),
                ('content_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='SHA-256 содержимого')),
                ('extracted_facts', models.JSONField(default=list, verbose_name='Кандидаты проверяемых фактов')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рерайта'), ('processing', 'Обрабатывается'), ('draft_ready', 'Черновик создан'), ('needs_review', 'Требует ручной проверки'), ('failed', 'Ошибка'), ('published', 'Опубликовано редактором'), ('skipped', 'Пропущено')], db_index=True, default='pending', max_length=20, verbose_name='Состояние обработки')),
                ('rewrite_model', models.CharField(blank=True, max_length=160, verbose_name='Модель рерайта')),
                ('prompt_version', models.CharField(blank=True, max_length=40, verbose_name='Версия промпта')),
                ('provider_response_id', models.CharField(blank=True, max_length=160, verbose_name='ID ответа провайдера')),
                ('source_facts', models.JSONField(blank=True, default=list, verbose_name='Факты из результата модели')),
                ('warnings', models.JSONField(blank=True, default=list, verbose_name='Предупреждения')),
                ('error_message', models.TextField(blank=True, verbose_name='Ошибка')),
                ('retry_count', models.PositiveIntegerField(default=0, verbose_name='Количество попыток')),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='Входные токены')),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='Выходные токены')),
                ('provider_cost_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True, verbose_name='Стоимость провайдера, USD')),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True, verbose_name='Последняя попытка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('created_news', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_import', to='news.news', verbose_name='Созданный черновик')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imported_items', to='news.newssource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Импортированный материал для AI-рерайта',
                'verbose_name_plural': 'Импортированные материалы для AI-рерайта',
                'ordering': ['-fetched_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='AIRewriteAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=40, verbose_name='Тип события')),
                ('message', models.CharField(max_length=500, verbose_name='Описание')),
                ('actor', models.CharField(default='system', max_length=160, verbose_name='Инициатор')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Безопасные детали')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_events', to='news.importednewsitem', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Событие AI-конвейера',
                'verbose_name_plural': 'События AI-конвейера',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='importednewsitem',
            index=models.Index(fields=['status', 'fetched_at'], name='news_import_status_bf4753_idx'),
        ),
    ]
